 BNF Grammar for Compiler Cringe

<nonzero> ::= "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"   /* digit without 0 */
<digit> ::= "0" | <nonzero>                                         /* all digits */
<digits> ::= <digit> | <digit> <digits>                             /* multiple digit numbers */
<natural> ::= <digit> | <nonzero> <digits>                          /* natural numbers, evading numbers starting with 0, ex. 076 */

<letter> ::=    "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" |
                "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z" |
                "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | 
                "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z"

<symbol> ::=    "|" | " " | "`" | "~" | "!" | "@" | "#" | "$" | "%" | "^" | "&" | "*" | "(" | ")" | 
                "-" | "_" | "=" | "+" | "[" | "]" | "{" | "}" | ";" | ":" | "<" | ">" | "," | "." |
                "/" | "?"

/* case handling for print, comments etc */
<char> ::= <letter> | <digit> | <symbol>
<char1> ::= <char> | "'"
<char2> ::= <char> | "\""
<text1> ::= "" | <char1> <text1>                                    /* text1 is for double quotes */
<text2> ::= "" | <char2> <text2>                                    /* text2 is for single quotes */
<literal> ::= "\"" <text1> "\"" | "'" <text2> "'"
<commentText> ::= <text1> | <text2>


FIXME wtf omg xqc thelei mia allh malakia symfwna me ekfwnhsh
<print> ::= "PRINT(" <literal> ")"

/* escape sequences, whitespace and comments*/
<escape_sequence> ::= <tab> | <newline> | <backslash>
<tab> ::= "\t"
<newline> ::= "\n"
<backslash> ::= "\\"

FIXME maybe whitespace doesnt work
<whitespace> ::= "" | " " <whitespace> | <comment>

<comment> ::= <slComment> | <mlComment>
<slComment> ::= "%" <commentText> <newline>
<mlComment> ::= "/*" <commentText> "*/"

/* variable dog */
<firstChar> ::= <letter> | "_"
<otherChar> ::= <letter> | <digit> | "_"
<string> ::= <otherChar> | <otherChar> <otherChar>

/* used for both variable names and function names */
<identifier> ::= <firstChar> | <firstChar> <string>                 /* for bison: [a-zA-Z] [a-zA-Z0-9_]* */

<variable> ::= <identifier> | <identifier> "[" <natural> "]"
<variables> ::= <variable> | <variable> "," <whitespace> <variables> 

<var_decl> ::= "VARS" "CHAR" <variables> | "VARS" "INTEGER" <variables>

/*enforcing order of operations (better read from bottom to top) */

<Expression> ::= <andExpression> | <Expression> "OR" <andExpression> /* OR expression and final */

<andExpression> ::= <comparison> | <andExpression> "AND" <comparison> /* AND expression */

<comparison> ::= <addition> | <comparison> ">" <addition> | <comparison> "<" <addition> | <comparison> "==" <addition> | <comparison> "!=" <addition> /* logikes ekfraseis */

<addition> ::= <multiplication> | <addition> "+" <multiplication> | <addition> "-" <multiplication> /* teleutaia arithmitiki prosthafaireseis */

<multiplication> ::= <negation> | <multiplication> "*" <negation> | <multiplication> "/" <negation> /* meta polmoi kai diaireseis */

<negation> ::= <power> | "-" <power> /* meta arnhtikoi (px - 9^2    PROSOXH OXI (-9)^2  ) */

<power> ::= <input> | <power> "^" <input> /* powers first */

<input> ::= <type> | <identifier> | "(" <Expression> ")" /* base type or an id */

<type> ::= <natural> | <commentText>  /* 2 base types */

TODO bnf functions
TODO arithmetic operations
TODO while loops
TODO for to step loops
TODO if then elseif else endif loops
TODO switch case default endswitch loops
TODO structs

/* gia argotera reserved keywords

    PROGRAM
    FUNCTION
    END_FUNCTION
    VARS
    CHAR
    INTEGER
    RETURN
    STARTMAIN
    ENDMAIN
    WHILE
    ENDWHILE
    FOR
    TO
    STEP
    ENDFOR
    IF
    THEN
    ELSEIF
    ELSE
    ENDIF
    AND
    OR
    SWITCH
    CASE
    DEFAULT
    ENDSWITCH
    PRINT
    BREAK
    TYPEDEF
    STRUCT
    ENDSTRUCT

*/